# Generated by Django 2.0.9 on 2018-12-13 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181213_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaInicio',
            field=models.TimeField(default=datetime.datetime(2018, 12, 13, 17, 14, 10, 470283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
