# Generated by Django 2.0.9 on 2018-12-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='cliente',
            field=models.ManyToManyField(related_name='_tecnico_cliente_+', to='api.Cliente'),
        ),
    ]
