# Generated by Django 2.0.9 on 2018-12-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181204_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='cliente',
            field=models.ManyToManyField(through='api.Orden', to='api.Cliente'),
        ),
    ]
