# Generated by Django 2.0.9 on 2018-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181204_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='cliente',
            field=models.ManyToManyField(to='api.Cliente'),
        ),
    ]
