# Generated by Django 2.0.9 on 2018-12-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181204_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='cliente',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cliente',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
            preserve_default=False,
        ),
    ]
