# Generated by Django 2.0.9 on 2018-12-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181205_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='tecnico',
        ),
    ]
