# Generated by Django 2.0.9 on 2018-12-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_orden_tecnico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='ascensor',
            new_name='idAscensor',
        ),
        migrations.AddField(
            model_name='orden',
            name='modeloAscensor',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tecnico'),
        ),
    ]
