# Generated by Django 2.0.9 on 2018-12-12 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181207_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaInicio',
            field=models.TimeField(default=datetime.datetime(2018, 12, 12, 11, 31, 19, 615047, tzinfo=utc)),
        ),
    ]
