# Generated by Django 2.0.9 on 2018-12-13 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181213_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='orden',
            name='horaInicio',
            field=models.TimeField(default=datetime.datetime(2018, 12, 13, 15, 30, 48, 477471, tzinfo=utc)),
        ),
    ]
