# Generated by Django 2.0.9 on 2018-12-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
